sudo: required
services:
- docker

before_install:

- docker build -t mywebfront/angular -f ./angular/Dockerfile ./angular

after_success:

# Login to the docker CLI using variables I set at travis online
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push to docker
- docker push mywebfront/angular

