version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
  angular:
    build:
      dockerfile: Dockerfile.dev
      context: ./angular
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5600:80'

