version: '3'
services:
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - "mongodata:/data/db"
  angular:
    build:
      dockerfile: Dockerfile.dev
      context: ./angular
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    environment:
    - MONGODB_HOST=mongodb
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5600:80'
volumes:
  mongodata:
