apiVersion: v1
kind: Service
metadata:
  name: angular-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: angular
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 31000
